default_agent: create_agent
agents:
  create_agent:
    name: create_agent
    language: python
    node_version: '20'
    entrypoint: src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/ec2-user/agentcore/ci/crawler-agent
    aws:
      execution_role: arn:aws:iam::632930644527:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-a3fa02f704
      execution_role_auto_create: false
      account: '632930644527'
      region: us-west-2
      ecr_repository: 632930644527.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-create_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: create_agent-CIyaxV2ktz
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:632930644527:runtime/create_agent-CIyaxV2ktz
      agent_session_id: cli-b2d01359a36c44adaae9383f490c67fb
    codebuild:
      project_name: bedrock-agentcore-create_agent-builder
      execution_role: arn:aws:iam::632930644527:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-a3fa02f704
      source_bucket: bedrock-agentcore-codebuild-sources-632930644527-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
